DEBUG = True

USERNAME = "myuser"
PASSWORD = "r76247wd"
SERVER = "172.21.0.2"
DB = "api_flask"

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True
