version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - pythonflask-network
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'api_flask'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'r76247wd'
      MYSQL_ROOT_PASSWORD: 'r76247wd'
    ports:
      - "3306:3306"
    networks:
    - pythonflask-network

networks:
  pythonflask-network:
    driver: bridge
